'use client';

import React, { useState } from 'react';
import { useTranslation } from '@/hooks/useTranslation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Eye, Download, ChevronDown, ChevronUp } from 'lucide-react';
import { GeneratedReport, ReportGenerationStatus } from '@/types/report.type';
import { TanStackTable } from '@/components/ui/tanstack-table';
import { Badge } from '@/components/ui/badge';
import { ColumnDef } from '@tanstack/react-table';
import { getReportTypeLabel } from '@/services/api/reports/generated-reports';

// Report Status Config - Make it reusable
export const REPORT_STATUS_CONFIGS: Record<
  ReportGenerationStatus,
  {
    variant: 'default' | 'secondary' | 'destructive' | 'outline';
    className: string;
    translationKey: string;
  }
> = {
  [ReportGenerationStatus.COMPLETED]: {
    variant: 'default',
    className: 'bg-green-500 hover:bg-green-600 text-white',
    translationKey: 'reports.status.completed',
  },
  [ReportGenerationStatus.FAILED]: {
    variant: 'destructive',
    className: 'bg-red-500 hover:bg-red-600 text-white',
    translationKey: 'reports.status.failed',
  },
  [ReportGenerationStatus.PROCESSING]: {
    variant: 'secondary',
    className: 'bg-blue-500 hover:bg-blue-600 text-white',
    translationKey: 'reports.status.processing',
  },
  [ReportGenerationStatus.PENDING]: {
    variant: 'outline',
    className: 'bg-yellow-500 hover:bg-yellow-600 text-white',
    translationKey: 'reports.status.pending',
  },
};

// Helper function for formatting dates
const formatDateTime = (dateString: string): string => {
  if (!dateString) return '-';
  try {
    const date = new Date(dateString);
    return date.toLocaleString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  } catch {
    return '-';
  }
};

interface GeneratedReportsTableProps<T extends GeneratedReport> {
  title?: string;
  data: T[];
  isLoading?: boolean;
  onShowDetails: (report: T) => void;
  onDownload: (report: T) => void;
  defaultCollapsed?: boolean;
  searchPlaceholder?: string;
  emptyMessage?: string;
  customColumns?: ColumnDef<T>[];
}

export function GeneratedReportsTable<T extends GeneratedReport>({
  title = 'reports.generatedReports',
  data,
  isLoading = false,
  onShowDetails,
  onDownload,
  defaultCollapsed = false,
  searchPlaceholder = 'reports.generated.searchPlaceholder',
  emptyMessage = 'reports.generated.noReports',
  customColumns = [],
}: GeneratedReportsTableProps<T>) {
  const { t } = useTranslation();
  const [isCollapsed, setIsCollapsed] = useState(defaultCollapsed);
  const [searchTerm, setSearchTerm] = useState('');

  // Default columns
  const defaultColumns: ColumnDef<T>[] = [
    {
      accessorKey: 'generateDate',
      header: t('reports.payment.columns.generateDate') || 'Generate Date',
      enableSorting: true,
      cell: ({ row }) => (
        <div className="whitespace-nowrap" title={row.original.generateDate}>
          {formatDateTime(row.original.generateDate)}
        </div>
      ),
    },
    {
      accessorKey: 'reportCompleteTime',
      header: t('reports.payment.columns.completeTime') || 'Complete Time',
      enableSorting: false,
      cell: ({ row }) => (
        <div className="whitespace-nowrap">
          {row.original.reportCompleteTime
            ? formatDateTime(row.original.reportCompleteTime)
            : '-'}
        </div>
      ),
    },
    {
      accessorKey: 'generatedByName',
      header: t('reports.payment.columns.generatedBy') || 'Generated By',
      enableSorting: false,
      cell: ({ row }) => (
        <div className="font-medium">
          {row.original.generatedByName || row.original.generatedBy}
        </div>
      ),
    },
    {
      accessorKey: 'reportType',
      header: t('reports.payment.columns.reportType') || 'Report Type',
      enableSorting: false,
      cell: ({ row }) => {
        const reportType = row.original.reportType;
        const labelKey = getReportTypeLabel(reportType);

        return <div className="max-w-[200px]">{t(labelKey) || reportType}</div>;
      },
    },
    {
      accessorKey: 'generationStatus',
      header: t('reports.payment.columns.status') || 'Status',
      enableSorting: true,
      cell: ({ row }) => {
        const status = row.original.generationStatus;
        const statusConfig = REPORT_STATUS_CONFIGS[status];

        return (
          <Badge
            variant={statusConfig.variant}
            className={statusConfig.className}
          >
            {t(statusConfig.translationKey) || status}
          </Badge>
        );
      },
    },
    {
      id: 'details',
      header: t('reports.payment.columns.details') || 'Details',
      cell: ({ row }) => (
        <Button
          variant="outline"
          size="sm"
          onClick={() => onShowDetails(row.original)}
          className="flex items-center gap-1"
        >
          <Eye className="h-4 w-4" />
          {t('reports.payment.showDetails') || 'Show Details'}
        </Button>
      ),
    },
    {
      id: 'actions',
      header: t('common.actions') || 'Actions',
      cell: ({ row }) => {
        const report = row.original;
        const isCompleted =
          report.generationStatus === ReportGenerationStatus.COMPLETED;

        return (
          <div className="flex items-center gap-2">
            {isCompleted && report.downloadUrl && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => onDownload(report)}
                className="flex items-center gap-1"
                title={t('reports.payment.downloadReport') || 'Download Report'}
              >
                <Download className="h-4 w-4" />
              </Button>
            )}
          </div>
        );
      },
    },
  ];

  const columns = customColumns.length > 0 ? customColumns : defaultColumns;

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between p-4">
        <div className="flex items-center gap-3">
          <CardTitle className="text-lg">
            {t(title) || 'Generated Reports'}
          </CardTitle>
        </div>
        <div className="flex items-center gap-2">
          {!isCollapsed && (
            <div className="text-sm text-muted-foreground flex items-center gap-2">
              <span className="px-2 py-1 bg-muted rounded">
                {data.length} {t('reports.mealTime.report') || 'report'}
              </span>
            </div>
          )}
          <Button
            variant="ghost"
            size="sm"
            className="h-8 w-8 p-0"
            onClick={() => setIsCollapsed(!isCollapsed)}
          >
            {isCollapsed ? (
              <ChevronDown className="h-4 w-4" />
            ) : (
              <ChevronUp className="h-4 w-4" />
            )}
          </Button>
        </div>
      </CardHeader>

      <div
        className={`overflow-hidden transition-all duration-300 ease-in-out
            ${
              isCollapsed
                ? 'max-h-0 opacity-0 translate-y-[-4px]'
                : 'max-h-[1000px] opacity-100 translate-y-0'
            }
          `}
      >
        <CardContent className="p-4 pt-0">
          {isLoading ? (
            <div className="text-center py-8">
              {t('common.loading') || 'Loading...'}
            </div>
          ) : data.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              {t(emptyMessage) || 'No reports generated yet'}
            </div>
          ) : (
            <TanStackTable<T>
              data={data}
              columns={columns}
              totalCount={data.length}
              pagination={{
                pageIndex: 0,
                pageSize: 10,
              }}
              onPaginationChange={() => {}}
              sorting={[]}
              onSortingChange={() => {}}
              columnFilters={[]}
              onColumnFiltersChange={() => {}}
              searchValue={searchTerm}
              onSearchChange={setSearchTerm}
              manualPagination={false}
              showPagination={true}
              showSearch={true}
              searchPlaceholder={
                t('reports.generated.searchPlaceholder') || 'Search reports...'
              }
              isLoading={isLoading}
            />
          )}
        </CardContent>
      </div>
    </Card>
  );
}
