import { ColumnDef } from '@tanstack/react-table';
import { GeneratedReport, ReportGenerationStatus } from '@/types/report.type';
import { Badge } from '@/components/ui/badge';
import { REPORT_TYPE_LABELS } from './constants';

// Report Status Colors Configuration
const REPORT_STATUS_CONFIGS: Record<
  ReportGenerationStatus,
  {
    variant: 'default' | 'secondary' | 'destructive' | 'outline';
    className: string;
    label: string;
  }
> = {
  [ReportGenerationStatus.COMPLETED]: {
    variant: 'default',
    className: 'bg-green-500 hover:bg-green-600 text-white',
    label: 'Completed',
  },
  [ReportGenerationStatus.FAILED]: {
    variant: 'destructive',
    className: 'bg-red-500 hover:bg-red-600 text-white',
    label: 'Failed',
  },
  [ReportGenerationStatus.PROCESSING]: {
    variant: 'secondary',
    className: 'bg-blue-500 hover:bg-blue-600 text-white',
    label: 'Processing',
  },
  [ReportGenerationStatus.PENDING]: {
    variant: 'outline',
    className: 'bg-yellow-500 hover:bg-yellow-600 text-white',
    label: 'Pending',
  },
};

// Props for columns with handlers
interface GeneratedReportsColumnsProps {
  onShowDetails?: (report: GeneratedReport) => void;
  onDownload?: (report: GeneratedReport) => void;
}

// Helper function to get report label safely
const getReportTypeLabel = (reportType: string): string => {
  // Type assertion to handle different report types
  return (
    REPORT_TYPE_LABELS[reportType as keyof typeof REPORT_TYPE_LABELS] ||
    reportType
  );
};

// Create columns function that accepts handlers
export const createGeneratedReportsColumns = (
  props?: GeneratedReportsColumnsProps,
): ColumnDef<GeneratedReport>[] => {
  // Format date/time helper
  const formatReportDateTime = (dateString: string): string => {
    if (!dateString) return '-';
    const date = new Date(dateString);
    return date.toLocaleString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // Format date only
  const formatReportDate = (dateString: string): string => {
    if (!dateString) return '-';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
  };

  // Format currency
  const formatReportCurrency = (amount: number): string => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return [
    {
      accessorKey: 'generateDate',
      header: 'Generate Date',
      enableSorting: true,
      size: 180,
      cell: ({ row }) => {
        const date = row.original.generateDate;
        return (
          <div className="whitespace-nowrap">
            <div className="font-medium">{formatReportDateTime(date)}</div>
            {row.original.reportCompleteTime && (
              <div className="text-xs text-muted-foreground mt-1">
                Completed:{' '}
                {formatReportDateTime(row.original.reportCompleteTime)}
              </div>
            )}
          </div>
        );
      },
    },
    {
      accessorKey: 'generatedByName',
      header: 'Generated By',
      enableSorting: false,
      size: 150,
      cell: ({ row }) => {
        const report = row.original;
        return (
          <div>
            <div className="font-medium">
              {report.generatedByName || report.generatedBy}
            </div>
            {report.generatedBy !== report.generatedByName && (
              <div className="text-xs text-muted-foreground">
                ID: {report.generatedBy}
              </div>
            )}
          </div>
        );
      },
    },
    {
      accessorKey: 'reportType',
      header: 'Report Type',
      enableSorting: false,
      size: 200,
      cell: ({ row }) => {
        const reportType = row.original.reportType;
        const label = getReportTypeLabel(reportType);

        return (
          <div className="max-w-[200px]">
            <div className="font-medium truncate">{label}</div>
            {row.original.filters?.from && row.original.filters?.to && (
              <div className="text-xs text-muted-foreground mt-1 truncate">
                {formatReportDateTime(row.original.filters.from)} -{' '}
                {formatReportDateTime(row.original.filters.to)}
              </div>
            )}
          </div>
        );
      },
    },
    {
      accessorKey: 'generationStatus',
      header: 'Status',
      enableSorting: true,
      size: 150,
      cell: ({ row }) => {
        const status = row.original.generationStatus;
        const config = REPORT_STATUS_CONFIGS[status];
        const hasError =
          status === ReportGenerationStatus.FAILED && row.original.errorMessage;

        return (
          <div className="space-y-1">
            <Badge variant={config.variant} className={config.className}>
              {config.label}
            </Badge>
            {hasError && (
              <div
                className="text-xs text-red-500 truncate max-w-[150px]"
                title={row.original.errorMessage}
              >
                Error
              </div>
            )}
          </div>
        );
      },
    },
  ];
};

// Default export for backward compatibility
export const generatedReportsColumns: ColumnDef<GeneratedReport>[] =
  createGeneratedReportsColumns();

// Hook to use columns with handlers
export const useGeneratedReportsColumns = (
  props?: GeneratedReportsColumnsProps,
) => {
  return createGeneratedReportsColumns(props);
};
